version: '3'
services:
  odoo:
    image: odoo:16.0
    hostname: odoo
    container_name: odoo
    ports:
      - 8069:8069
    volumes:
      - $PWD/odoo-conf/odoo.conf:/etc/odoo/odoo.conf
    networks:
      - odoo
    healthcheck:
      test: curl --fail http://localhost:8069/web/database/selector || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      postgres-odoo:
        condition: service_healthy
    command: -d odoo -i stock,account,purchase,sale_management && populate --size medium 
  postgres-odoo:
    image: postgres:15.1-alpine
    hostname: postgres-odoo
    container_name: postgres-odoo
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=odoo
    volumes:
      - $PWD/postgres_odoo:/var/lib/postgresql/data
    networks:
      - odoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: -c log_statement=all
  metabase-odoo:
    image: metabase/metabase-enterprise:v1.45.2
    container_name: metabase-odoo
    hostname: metabase-doo
    volumes: 
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment: 
      - "MB_DB_TYPE=postgres"
      - "MB_DB_DBNAME=metabase"
      - "MB_DB_PORT=5432"
      - "MB_DB_USER=metabase"
      - "MB_DB_PASS=mysecretpassword"
      - "MB_DB_HOST=postgres-metabase"
    cpus: 1
    mem_limit: 2048m
    networks: 
      - odoo
    depends_on: 
      postgres-metabase:
        condition: service_healthy
      odoo:
        condition: service_healthy
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  setup-metabase:
    image: bash:5.1.16
    container_name: setup-metabase
    volumes:
      - $PWD/setup-metabase:/tmp
    networks:
      - odoo
    depends_on:
      metabase-odoo:
        condition: service_healthy
    command: sh /tmp/metabase-setup.sh metabase-odoo:3000
    cpus: 1
    mem_limit: 128m
  postgres-metabase:
    image: postgres:15.1-alpine
    hostname: postgres-metabase
    container_name: postgres-metabase
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=metabase
    volumes:
      - $PWD/postgres_metabase:/var/lib/postgresql/data
    networks:
      - odoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase -d metabase"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  odoo:
    driver: bridge